const companies = [
    {
        name: "",
        founders: "",
        about: "",
        rating: "",
        location: "",
        photo: "",
        isFeatured: ,
    },
    {
        name: "",
        founders: "",
        about: "",
        rating: "",
        location: "",
        photo: "",
        isFeatured: ,
    },
   
    {
        name: "",
        founders: "",
        about: "",
        rating: "",
        location: "",
        photo: "",
        isFeatured: ,
    },
    {
        name: "",
        founders: "",
        about: "",
        rating: "",
        location: "",
        photo: "",
        isFeatured: ,
    },
    {
        name: "",
        founders: "",
        about: "",
        rating: "",
        location: "",
        photo: "",
        isFeatured: ,
    },
    {
        name: "",
        founders: "",
        about: "",
        rating: "",
        location: "",
        photo: "",
        isFeatured: ,
    },
    {
        name: "",
        founders: "",
        about: "",
        rating: "",
        location: "",
        photo: "",
        isFeatured: ,
    },
    {
        name: "",
        founders: "",
        about: "",
        rating: "",
        location: "",
        photo: "",
        isFeatured: ,
    },
    {
        name: "",
        founders: "",
        about: "",
        rating: "",
        location: "",
        photo: "",
        isFeatured: ,
    },
    {
        name: "",
        founders: "",
        about: "",
        rating: "",
        location: "",
        photo: "",
        isFeatured: ,
    }
]

module.exports = products
